[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  branch = "master"
  name = "k8s.io/client-go"

[[constraint]]
  branch = "master"
  name = "k8s.io/kubectl"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "v0.0.3"

[prune]
  go-tests = true
  unused-packages = true
